### ISSUE TITLE
os_image_label parameter returns old ubuntu version

### ISSUE THREAD

**Issue by ravbaba** [Azure/packer-azure#108]
when I set:
```
"os_image_label": "Ubuntu Server 14.04 LTS"
```
and run packer build then I can notice that used image source is not the latest one
```
azure: Image source is OS image "b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04-LTS-amd64-server-20140724-en-us-30GB"
```

When I try create VM via azure interface with ubuntu image there is an option which allows you to choose version release date and currently the latest one is 9/9/2015 (that is the date which I can choose via interface).

below one is returned with 
```azure vm image list``` command
```
b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_3-LTS-amd64-server-20150908-en-us-30GB
```

Is it possible to set it somewhere or that option has been missed?

**Comment by ravbaba** [comment]
I've just changed it to
```
"os_image_label": "Ubuntu Server 14.04.3-LTS"
```

and now I get the latest one.

**Comment by paulmey** [comment]
Indeed, it does an exact match on label: https://github.com/MSOpenTech/packer-azure/blob/master/packer/builder/azure/FindImage.go#L43

Does that resolve your issue?

**Comment by ravbaba** [comment]
@paulmey - yes, using ```"os_image_label": "Ubuntu Server 14.04.3-LTS"``` resolves my issue. It would be nice to mention that somewhere in a doc because it is not such obvious that you need to use a hyphen in the label especially when example shows ```"os_image_label": "Ubuntu Server 14.04 LTS"``` the label without a hyphen, nothing big but confusing.

**Comment by paulmey** [comment]
Agreed. I've been thinking for a while what the best way would be to select the OS image. The name is a bit obscure, I'd never makes someone type it, but the label doesn't always work well either, such as in this case. BTW, these names are created by the publishers, so things like this hyphen are not something that is under central control...

**Comment by rchalumeau** [comment]
Hi @paulmey,  

I fell in a similar case. My use case is that I would want to be able able to build an image immutable in time (for debugging purpose for instance). 

As an example, I have those indeed obscur names: 
5112500ae3b842c8b9c604889f8753c3__OpenLogic-CentOS-71-20150605
5112500ae3b842c8b9c604889f8753c3__OpenLogic-CentOS-71-20150731
If I have built my user image with the 20150605 version, so configure the packer file with an exhaustive identifier of the os version, ie i'd like to rebuild it without getting the 20150731 one.   

Yet, as the label is the same for both ("OpenLogic 7.1"), it is not usable in my case. 

When I check the list from azure-cli, the long hashed prefix which makes the name obscur doesn't bring any info. So, wouldn't it be possible to have an "os_image_name" parameter based on the last part of the name, ie in my case : OpenLogic-CentOS-71-20150605. 
It would make the name less obscur and more precise than the label.

**Comment by paulmey** [comment]
I like the suggestion. However, I don't want to rely on format of the name that specifically (it's not guaranteed). But maybe a substring match or regex match would be a workable solution? You could still use the value you propose above "OpenLogic-CentOS-71-20150605" to match the name "5112500ae3b842c8b9c604889f8753c3__OpenLogic-CentOS-71-20150605".
If you have time, feel free to send a PR. I'm afraid I won't get to this in the next week or so...

**Comment by rchalumeau** [comment]
That's exactly what I had in mind. 
It is by the way how it is done with Google COmpute Engine. 

So, I'll open a PR. 
No problem for the time, I have a workaround to solve my use case (store an OS image version as a custom image in storage to have it under control). 
Thanks  for your work
