### ISSUE TITLE
waagent on CoreOS is not found

### ISSUE THREAD

**Issue by pinterb** [Azure/packer-azure#111]
Thank you for taking the time to work on this.  

It looks like it's assumed waagent is located under **/usr/sbin**.  But on CoreOS, waagent is located under **/usr/share/oem/bin**.

**Comment by paulmey** [comment]
Good catch, let me see how we should resolve this...

**Comment by boumenot** [comment]
I haven't seen an update on this issue, so I assume it has been addressed.  Please reopen as necessary.
