### ISSUE TITLE
azure: Waiting for SSH to become available...

### ISSUE THREAD

**Issue by tabbi89** [Azure/packer-azure#115]
What I see is that the newly created VM is running but I cannot connect to it:

==> azure: Waiting for SSH to become available...
2015/11/01 23:16:08 packer-builder-azure: 2015/11/01 23:16:08 TCP connection to SSH ip/port failed: dial tcp: unknown port tcp/%!d(string=22)
2015/11/01 23:16:13 packer-builder-azure: 2015/11/01 23:16:13 TCP connection to SSH ip/port failed: dial tcp: unknown port tcp/%!d(string=22)
2015/11/01 23:16:18 packer-builder-azure: 2015/11/01 23:16:18 TCP connection to SSH ip/port failed: dial tcp: unknown port tcp/%!d(string=22)

Any idea WHY ? I am using the latest packer version 0.8.6

**Comment by paulmey** [comment]
What version of the packer azure plugins are you using?
This is an old bug (#59) and should be fixed in recent versions. Can you grab the latest binaries from https://github.com/Azure/packer-azure/releases/tag/prerelease and see if this issue still occurs?

**Comment by tabbi89** [comment]
I will try but I have to build it manually on mac os x, after that I will let You know.

**Comment by tabbi89** [comment]
Everything seems fine with latest binaries, Thanks a lot
