### ISSUE TITLE
Create ARM image from user VHD image

### ISSUE THREAD

**Issue by rchalumeau** [Azure/packer-azure#209]
Hi, 

Is there any plan to implement, an ARM image from a VHD URI, almost as in ASM mode (user_image_label like) ?  

Is it planned to replace the struct : 
```
"imageReference": {
  "publisher": "[parameters('imagePublisher')]",
  "offer": "[parameters('imageOffer')]",
  "sku": "[parameters('imageSku')]",
  "version": "latest"
},
"osDisk": { 
  [...] 
}
```
with something like (just like the generated json template by the way): 
```
"osDisk": {
  "image": {
    "uri": "[parameters('imageUri')]"
  },
  [...] 
},
```

Can it be a generic way to handle the source images (by generating the URI from publisher, offer, sku) ? 

Romain

**Comment by boumenot** [comment]
In general, we would like to maintain parity between the two as much as possible.  Accepted.

**Comment by JamieCressey** [comment]
+1

**Comment by miketypeguy** [comment]
+1

**Comment by mattjcorner** [comment]
+1

**Comment by bkarypid** [comment]
+1

**Comment by wesmiles** [comment]
+1

**Comment by jamielennox1** [comment]
+1

**Comment by RHollinshead** [comment]
+1

**Comment by dnorth98** [comment]
+1

**Comment by tasquith** [comment]
@boumenot is this now being tracked in the official packer repo?

Tom

**Comment by boumenot** [comment]
I haven't re-opened any of the issues here in the official Packer repo.  I actively follow both, so I was not concerned about moving them all over.  This issue might be one of the few that is worth moving though due to its popularity.

I'm planning on working on this next, but I don't have an ETA.

**Comment by tasquith** [comment]
Had a bit of time spare this evening so thought I'd have a go! Any comments/suggestions would be gratefully received.

Tom

**Comment by boumenot** [comment]
Support for this has been [committed][1] to the official Packer repository, and will be available with the next release.

[1]: https://github.com/mitchellh/packer/pull/3575
