### ISSUE TITLE
Support Device Login

### ISSUE THREAD

**Issue by boumenot** [Azure/packer-azure#210]
The process of creating an SPN is complicated, and inhibits "first time users" from running packer.  We should support device login, which will make this much easier.  Device login isn't very suitable for automation, but greatly improves the out-of-box-experience.

Our Azure friend @ahmetalpbalkan has already written the [code](https://github.com/ahmetalpbalkan/machine/commit/e147c315df1a5d6db464662ca4134dc1faf08823), so we've already got a leg up.

**Comment by ahmetalpbalkan** [comment]
yeah lmk if u need help

**Comment by boumenot** [comment]
Fixed by #217.
