### ISSUE TITLE
Error running packer build against azure ARM

### ISSUE THREAD

**Issue by lbielefeld** [Azure/packer-azure#215]
We're trying run packer against azure ARM for the first time, and are blocked by this error.  Any idea how to proceed?

$GOPATH/bin/packer build -var-file vars.json packer_azure.json 
azure-arm output will be in this color.

==> azure-arm: Preparing builder ...
    azure-arm: Creating Azure Resource Manager (ARM) client ...
Build 'azure-arm' errored: storage/AccountsClient:ListKeys 400 Failure responding to request -- Original Error: azure: Service returned an error. Code="InvalidApiVersionParameter" Message="The api-version '2015-06-15' is invalid. The supported versions are '2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'." Status=400

==> Some builds didn't complete successfully and had errors:
--> azure-arm: storage/AccountsClient:ListKeys 400 Failure responding to request -- Original Error: azure: Service returned an error. Code="InvalidApiVersionParameter" Message="The api-version '2015-06-15' is invalid. The supported versions are '2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'." Status=400

**Comment by boumenot** [comment]
I see that the error message is about the storage API, but this is the first time I've seen this issue.  Do you have any more context on this error?  Are you able to share your JSON documents?

The fact that you're being rejected due to an API version issue is odd, which cloud environment are you connecting to, i.e. Public Cloud, Fairfax, or China?

**Comment by lbielefeld** [comment]
This turned out to be a user error.  The variable name specifying the storage group in the var-file did not match the variable name in the json file.  Not a particularly useful error message.

**Comment by boumenot** [comment]
Thank you for taking the time to circle back and share the root cause.  I know there's work we can do to make this error clearer.  I'll keep this issue open until we do.

**Comment by boumenot** [comment]
Development has moved over to the official Packer repository.  The latest release of Packer (v0.10.1) has [code](https://github.com/mitchellh/packer/pull/3483) to better debug.  I still don't know the root cause, but perhaps this will help me to find it.
