### ISSUE TITLE
Premium stroage support

### ISSUE THREAD

**Issue by tc0312** [Azure/packer-azure#223]
Since Premium Storage doesn't support page, Is it possible to use packer-azure with Premium Storage  VMs?
Thanks.

**Comment by boumenot** [comment]
Sorry for the late response, I"m just returning...

I haven't tried this scenario, but packer-azure does not operate at a level where it makes this distinction.  All of the APIs it operates with don't care (to my knowledge).  Do you a gist of the Packer config that you can share so I can validate it.

**Comment by tc0312** [comment]
You are correct. It's working. Closing the issue.
