### ISSUE TITLE
QUESTION - Can I use an existing packer created VHD as a source for another?

### ISSUE THREAD

**Issue by tasquith** [Azure/packer-azure#249]
Hi,

I'm trying to replicate a workflow we have on AWS, where we use packer to create a custom base AMI from the published centos AMI, then use the custom AMI to seed the creation of two more specialised images using packer.

Is the above possible using the azure ARM builder? 

Can packer use an existing packer created VHD as a source to create another image, as opposed to using a source published from the marketplace?

I can't seem to find anything to suggest that this is supported, but I'm just unsure if I've missed something.

Kind Regards,

Tom

**Comment by boumenot** [comment]
This is not possible with ARM version of today.  This issue is being tracked in #209, and the community has bumped it several times.  This is on my short list, but I do not have an ETA at this time.

**Comment by tasquith** [comment]
Thanks for the quick response! I'll keep an eye out!

**Comment by jakubigla** [comment]
Hi @boumenot 
Is it still the case? Sorry to say that, but if I can't use my golden image as a base for my other images, then I find this repository a bit useless... ;(

**Comment by boumenot** [comment]
This repo is useless.  It says deprecated in the README as a way to signify that.  The Azure builder has been merged into the official Packer repository, and that is where all development occurs.
