### ISSUE TITLE
Questions: chroot for ARM and how to get temporary VM name and Resource Group

### ISSUE THREAD

**Issue by mbentancour** [Azure/packer-azure#250]
Are there any plans to have a chroot builder like the one available for AWS? We have some scripts that we use in the AWS chroot builder and it would be really helpful to have the same for Azure. 

The other question is if there is any way to get the VM name and the Resource group name of the temporary build. Since there is no chroot option, we are simulating it by finding the temp VM, deleting it, attaching the disk to the packer builder VM, and re-creating it after so that packer can continue. The problem is that if there is more than one build process running at the same time, we have no way of knowing which machine corresponds to each script.

**Comment by boumenot** [comment]
We prioritize and implement based on community feedback, so consider this the first vote we've had for a chroot builder.

The resource group and VM name are randomly assigned at run time, and other than the logs they are not exposed.  The resource group and VM name are logged, and could be parsed out.  There's a request to re-use existing an resource group and resources when executing packer, which may help you.

I don't understand fully your second question fully, or rather I do not understand the process.  It's interesting.  The existing packer-azure process will delete the VM at the end, but it sounds like your intercepting and stopping that process.  (If I understand correctly, this seems like a lot of pain that chroot would just solve for you.)

**Comment by boumenot** [comment]
I logged #251 to track the chroot request.

**Comment by mbentancour** [comment]
Thanks for your reply. The process is quite complicated, and indeed a chroot builder would solve it.

The process is not interrupted because a VM with the same name, in the same resource group, and with the original disk attached is created at the end of the pseudo-chroot process. This is done only so that packer can continue to run.
