### ISSUE TITLE
unknown configuration key: "os_type"

### ISSUE THREAD

**Issue by aarsan** [Azure/packer-azure#252]
I am using packer version 0.10.0 and attempting to use this plugin. I understand that azure-arm is now built in to packer but deploying windows is not yet supported (from my understanding), which is why i'm using this plugin. I have placed the plugin files in the same directory as packer.exe and am trying to use the template here:

https://github.com/Azure/packer-azure/blob/master/config_examples/arm/WindowsServer-2012-R2.json 

but I keep getting "unknown configuration key: "os_type"" 

I'm sure this is an error on my part but I can't seem to figure out what it is. 

thanks!

Update: Let me also mention that I am using the version of the plugin downloaded from the release tab.

**Comment by liv3d** [comment]
The plugin doesn't provide support for `azure-arm` as this is a builtin builder in Packer, which at this time only supports Linux

There is an `azure` type which this plugin provides support for, see: https://github.com/Azure/packer-azure/blob/master/config_examples/packer-azure_Win2012r2.json

**Comment by aarsan** [comment]
Thanks!

**Comment by boumenot** [comment]
I sent a [PR](https://github.com/mitchellh/packer/pull/3461) to add WIndows support for Azure to the official Packer repository.  All development on ARM will move to the official Packer repository going forward.  ASM (Service Management aka SM aka the old API) will continue on in this repository.

**Comment by aarsan** [comment]
Any idea when it will be merged? And, after it is merged, any idea how long before they'd cut a release?

**Comment by liv3d** [comment]
> Device login support. User doesn't have to create an SPN to actually use the builder.

@boumenot Is there a way in the new build to use a setting/key file (or setup oauth/api keys?) Moving forward, we're looking to automate the builds and clicking a link to login is going to cause issues here

**Comment by boumenot** [comment]
The short answer is I don't know.

It is currently under review by the team.  I don't know when the next release will be cut, but the last two were frequent, but the ones before were not.

**Comment by boumenot** [comment]
@liv3d Yes.  If you're going to automate the build, which is what we expect most people to do, the correct way is via an SPN.  The use of a SPN avoids any need for an interactive login.

If you just want to try out Packer on Azure then Device Login is a good way to start.  The process of creating an SPN can be daunting, and delays gratification :smile:.  We introduced Device Login support so people could actually see if Packer would fit their needs without having to create an SPN.
