### ISSUE TITLE
Code Deployemnt failed

### ISSUE THREAD

**Issue by nikhilmutkekar** [Azure/packer-azure#263]
{
  "variables": {
    "client_id": "1c*********8",
    "client_secret": "******",
    "resource_group": "a*****p",
    "storage_account": "a******e",
    "subscription_id": "5******d",
    "tenant_id": "7*****f",
    "object_id": "6****2"
  },
  "builders": [{
    "type": "azure-arm",

    "client_id": "{{user `client_id`}}",
    "client_secret": "{{user `client_secret`}}",
    "resource_group_name": "{{user `resource_group`}}",
    "storage_account": "{{user `storage_account`}}",
    "subscription_id": "{{user `subscription_id`}}",
    "object_id": "{{user `object_id`}}",
	"tenant_id": "{{user `tenant_id`}}",

            "capture_container_name": "images",
            "capture_name_prefix": "packer",

            "os_type": "Windows",
            "image_publisher": "MicrosoftWindowsServer",
            "image_offer": "WindowsServer",
            "image_sku": "2012-R2-Datacenter",

            "communicator": "winrm",
            "winrm_use_ssl": "true",
            "winrm_insecure": "true",
            "winrm_timeout": "3m",
            "winrm_username": "packer",

            "location": "West US",
            "vm_size": "Standard_A2"
        }
    ],
    "provisioners": [
        {
            "type": "powershell",
            "inline": [
                "dir c:\\"
            ]
        }
    ]
}

Output : 

2016/08/23 02:53:39 ui error: ==> azure-arm: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed': Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details."

--> azure-arm: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed': Code="DeploymentFailed" Message="At least one resource deployment
operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details."

Build is not successful "Windows 2012 R2 Datacenter".
I'm using latest master/build which was pointed by in here [https://github.com/Azure/packer-azure/issues/262].

**Comment by boumenot** [comment]
Please re-open this issue against the official Packer repository so we can better track the issue.  Please include a gist of the debug output.

**Comment by nikhilmutkekar** [comment]
Here goes the debug output.  [https://gist.githubusercontent.com/nikhilmutkekar/dfd5781c9ffe57f6abf884e7d57bc8d9/raw/c88ed3294e826fe5be15122ad97f8a7bcc00f775/log.txt]
