### ISSUE TITLE
when the new stable build is available for issue #262.

### ISSUE THREAD

**Issue by nikhilmutkekar** [Azure/packer-azure#265]
As referenced in #262 "Failed to get Certificate URL" for the build 0.10.1. The developer pointed to a build which was not officially released to solve the issue . Since official Packer repository is not available which will address issue #262, When would the official new packer build containing the fix would be released  ?

**Comment by boumenot** [comment]
Azure ARM is supported in the official Packer repository.  Please log issues for Azure ARM at https://github.com/mitchellh/packer.
