### ISSUE TITLE
when to use type 'azure' and when 'azure-arm'?

### ISSUE THREAD

**Issue by dothebart** [Azure/packer-azure#269]
I've learned so far that there is an ARM called plugin that was merged upstream introducing the `type` `azure-arm` while this provides `azure`. 
Whats the difference between the two? Which one is to be prefered in which situation?
Does one of these offer publishing images into the Azure store?

**Comment by boumenot** [comment]
Old vs. New.  The merged plugin supports the new API (arm aka Azure Resource Manager), and this version supports the old API (sm aka Service Management).  The new plugin is the preferred solution.  This repository is maintained, but no new development is being done.  All new work happens in the official Packer repository for the azure-arm plugin.

Either one will produce a VHD that can be published, but there's no support in Packer for automatically publishing into the Azure store.

**Comment by dothebart** [comment]
Thanks a lot for the clear statement. maybe something that could be there in the readme ;-)

**Comment by dothebart** [comment]
oh, one more question, since the packer repo mentions the nodejs azure shell, would that support uploading to the store?

**Comment by boumenot** [comment]
Sorry, I have never published an image into the Azure marketplace, so I don't have any experiences to share with you.  

I do know that SuSE developed a tool for publishing images to the Marketplace, and claim a much nicer workflow for Linux based developers.  (It's isn't clear to me what platform you are on, but suggestions don't hurt.)  See [azurectl](https://github.com/SUSE/azurectl) for details.
