### ISSUE TITLE
Split builder to allow building vm images as well as just vhd's

### ISSUE THREAD

**Issue by paulmey** [Azure/packer-azure#46]
Create packer-azure-builder-vmimage and packer-azure-builder-vhd. The current behavior of packer-azure-builder is that of packer-azure-builder-vmimage

**Comment by JamieCressey** [comment]
+1 we currently build all our images using `capture_role` opposed to `capture`, and our deployment scripts are configured as such. Therefore, being able to build via Packer by OS Image rather than VM Image would be a massive benefit.

**Comment by paulmey** [comment]
ok, so a three way split then... vhd, osimage, vmimage :-)
