### ISSUE TITLE
Make vagrant post-processor work with Azure

### ISSUE THREAD

**Issue by mohitarora** [Azure/packer-azure#50]
Packer POST-PROCESSORS should be supported so that vagrant boxes can be created.

**Comment by paulmey** [comment]
What combination of builders and post-processors doesn't work for you?

**Comment by mohitarora** [comment]
I am trying to use vagrant post processor https://www.packer.io/docs/post-processors/vagrant.html but it doesn't work

**Comment by paulmey** [comment]
Ah... As you may notice, Azure is not on the list of supported providers for the Vagrant post-processor. This support needs to be added in the github.com/mitchellh/packer, it cannot be fixed in this packer-azure.

**Comment by mohitarora** [comment]
Sure, I will see if i can add that.

**Comment by boumenot** [comment]
No progress has been made on this issue in > a year, so I'm closing.  The ARM builder is the way forward for Packer on Azure, so please re-test against this version.
