### ISSUE TITLE
Combination of Existing Provisioners should work with the new provisioners added for Azure

### ISSUE THREAD

**Issue by mohitarora** [Azure/packer-azure#51]
We were trying to use puppet provisioner with azure-custom-script-extension. Puppet provisioner provides lot of benefits like auto mounting of modules and manifests directory. There can be a work around using azure-powershell provisioner which we are trying. 

It would be great if out of the box combination of provisioners work.

**Comment by paulmey** [comment]
What is the unexpected behavior you're seeing? I'm not entirely familiar with the azure-custom-script-extension, but I'll gladly help fix it anyway... :-)

**Comment by mohitarora** [comment]
unexpected behavior is that puppet provisioner is not event executed :)

**Comment by paulmey** [comment]
Are you deploying Linux or Windows? On Linux, I'd advise to use the built-in Packer shell provisioner. The custom script is a solution for Windows not having a ssh shell-like provisioner in Packer.

If you are deploying Windows, packer-azure expects only one custom-script provisioner entry. It adds sysprep at the end of the script (https://github.com/MSOpenTech/packer-azure/blob/master/packer/provisioner/azureVmCustomScriptExtension/provisioner.go#L186-191).
I think we should move this out of the provisioner. Then, together with #54 it might work...?

**Comment by mohitarora** [comment]
We are using windows.

We can live with just one script and in the end of the script we can execute our puppet run but #54 is the key in that scenario.

**Comment by boumenot** [comment]
No progress has been made on this issue in > a year, so I'm closing.  The ARM builder is the way forward for Packer on Azure, so please re-test against this version.
