### ISSUE TITLE
Provisioner type - powershell-azure not working

### ISSUE THREAD

**Issue by mohitarora** [Azure/packer-azure#53]
Is Provisioner type - powershell-azure even supported? I can see it in examples, one of the example is https://github.com/MSOpenTech/packer-azure/blob/master/config_examples/packer-azure_Win2012r2_inet.json but when i execute it, it simply doesn't work.

As per code, powershell-azure is not even supported. When i check the following file, it doesn't even import powershell/communicator.go which indicates that only provisioner type azure-custom-script-extension is supported.

https://github.com/MSOpenTech/packer-azure/blob/master/packer/builder/azure/driver_restapi/targets/win/step_set_provision_infrastructure.go

Am i missing something? I am using the current release version.

**Comment by paulmey** [comment]
I'll take a look. A lot has changed in the code in the past few weeks. We removed the powershell builder in favor of the REST API builder. You may very well be right that the powershell provisioner is no longer functional. Do you have a use case that requires this provisioner over the custom-script provisioner?

**Comment by mohitarora** [comment]
No, We don't have a use case but the key will be #54 to work.

Poweshell provisioner supports folder upload but custom-script-extension doesn't

**Comment by paulmey** [comment]
should we be using [packer-community/packer-windows-plugins](https://github.com/packer-community/packer-windows-plugins) for windows images? That may fix a lot of things at the same time? 
cc: @ahmetalpbalkan @Snesha

**Comment by boumenot** [comment]
The ARM builder has full support for WinRM communicator and the PowerShell provisioner.
