### ISSUE TITLE
ARM support for storage container

### ISSUE THREAD

**Issue by nitrat7** [Azure/packer-azure#94]
support for storage account managed by Storage Resource Provider.
(ARM Mode).

**Comment by paulmey** [comment]
That will mean ARM support for everything, which is indeed something we should be working on. I think we may need to support both ARM and ASM for a while so this will need to be an option in config or separate builders.

**Comment by nitrat7** [comment]
I think, an option in json config would be great, so that a switch can be easily done...

**Comment by paulmey** [comment]
Let's keep the issue open to track this work. Thanks for bringing this up.

**Comment by cure** [comment]
I'd also love to see ARM Packer support. We use Packer to build images for deploying Arvados (https://arvados.org) on various clouds. On AWS and GCP, that is pretty much automated and works very well. For Azure (we use ARM), we have to go through a much more manual and time consuming procedure to build the images.

**Comment by doktoric** [comment]
+1

**Comment by jamesyouknowwho** [comment]
+1

**Comment by rarsan** [comment]
+1

**Comment by paulmey** [comment]
We're working on this. Expect a PR in the coming weeks... right, @boumenot? :wink:

**Comment by lalyos** [comment]
+1

**Comment by paulmey** [comment]
FYI, we've started the series of PR's that support building ARM VM's with packer-azure. We'll try to reference this issue one each of them. I'd encourage everyone to comment on the PR's (even if we've already merged them) to make sure that what we end up with meets the expectations. -- Thanks!

**Comment by gmitre** [comment]
+1

**Comment by boumenot** [comment]
We have ARM support.
