### ISSUE TITLE
Support latest packer release

### ISSUE THREAD

**Issue by lilirui** [Azure/packer-azure#95]
Hi,

Just want to confirm what is the roadmap to support the latest Packer version?

**Comment by paulmey** [comment]
The roadmap is to always support the latest Packer release.

**Comment by paulmey** [comment]
I've recently updated the prerelease bits, which are at least compiled against the most recent packer source. My expectation would be that it should work with the latest release as well.

**Comment by lilirui** [comment]
Yes it works.
